package com.ascbank.client;

import com.ascbank.model.Gantt;
import com.ascbank.model.GanttExample;
import com.ascbank.repository.mybatis.MyBatisRepository;

import java.util.List;
import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface GanttMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gantt
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int countByExample(GanttExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gantt
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int deleteByExample(GanttExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gantt
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gantt
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int insert(Gantt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gantt
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int insertSelective(Gantt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gantt
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    List<Gantt> selectByExample(GanttExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gantt
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    Gantt selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gantt
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int updateByExampleSelective(@Param("record") Gantt record, @Param("example") GanttExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gantt
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int updateByExample(@Param("record") Gantt record, @Param("example") GanttExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gantt
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int updateByPrimaryKeySelective(Gantt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gantt
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int updateByPrimaryKey(Gantt record);
}