package com.ascbank.client;

import com.ascbank.model.Navigation;
import com.ascbank.model.NavigationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NavigationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int countByExample(NavigationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int deleteByExample(NavigationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int insert(Navigation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int insertSelective(Navigation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    List<Navigation> selectByExample(NavigationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    Navigation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int updateByExampleSelective(@Param("record") Navigation record, @Param("example") NavigationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int updateByExample(@Param("record") Navigation record, @Param("example") NavigationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int updateByPrimaryKeySelective(Navigation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table navigation
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int updateByPrimaryKey(Navigation record);
}