package com.ascbank.client;

import com.ascbank.model.Shortcut;
import com.ascbank.model.ShortcutExample;
import com.ascbank.repository.mybatis.MyBatisRepository;

import java.util.List;
import org.apache.ibatis.annotations.Param;

@MyBatisRepository
public interface ShortcutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shortcut
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int countByExample(ShortcutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shortcut
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int deleteByExample(ShortcutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shortcut
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shortcut
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int insert(Shortcut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shortcut
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int insertSelective(Shortcut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shortcut
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    List<Shortcut> selectByExample(ShortcutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shortcut
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    Shortcut selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shortcut
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int updateByExampleSelective(@Param("record") Shortcut record, @Param("example") ShortcutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shortcut
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int updateByExample(@Param("record") Shortcut record, @Param("example") ShortcutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shortcut
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int updateByPrimaryKeySelective(Shortcut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shortcut
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int updateByPrimaryKey(Shortcut record);
}