package com.ascbank.client;

import com.ascbank.model.UrlFilter;
import com.ascbank.model.UrlFilterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UrlFilterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_filter
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int countByExample(UrlFilterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_filter
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int deleteByExample(UrlFilterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_filter
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_filter
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int insert(UrlFilter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_filter
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int insertSelective(UrlFilter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_filter
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    List<UrlFilter> selectByExample(UrlFilterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_filter
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    UrlFilter selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_filter
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int updateByExampleSelective(@Param("record") UrlFilter record, @Param("example") UrlFilterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_filter
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int updateByExample(@Param("record") UrlFilter record, @Param("example") UrlFilterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_filter
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int updateByPrimaryKeySelective(UrlFilter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_filter
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    int updateByPrimaryKey(UrlFilter record);
}