/**
 *
 */
package com.ascbank.model.base;

/**
 * @author jie
 *
 */
public interface CaptchaValidetorModel {
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.captcha
	 *
	 * @return the value of user.captcha
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */

	public String getCaptcha();
}
