package com.ascbank.model;

import java.util.Date;

import com.ascbank.model.base.PKEntity;

public class Article extends PKEntity<Long> {
	/**
	 *
	 */
	private static final long	serialVersionUID	= 763429747182860831L;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column article.context
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	private String				context;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column article.menu_id
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	private Long				menuId;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column article.uploadtime
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	private Date				uploadtime;
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column article.context
	 *
	 * @return the value of article.context
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	public String getContext() {
		return context;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column article.menu_id
	 *
	 * @return the value of article.menu_id
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	public Long getMenuId() {
		return menuId;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column article.uploadtime
	 *
	 * @return the value of article.uploadtime
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	public Date getUploadtime() {
		return uploadtime;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column article.context
	 *
	 * @param context
	 *            the value for article.context
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	public void setContext(String context) {
		this.context = context == null ? null : context.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column article.menu_id
	 *
	 * @param menuId
	 *            the value for article.menu_id
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	public void setMenuId(Long menuId) {
		this.menuId = menuId;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column article.uploadtime
	 *
	 * @param uploadtime
	 *            the value for article.uploadtime
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	public void setUploadtime(Date uploadtime) {
		this.uploadtime = uploadtime;
	}
}