package com.ascbank.model;

import java.util.Date;

import org.apache.solr.client.solrj.beans.Field;
import org.springframework.data.solr.core.mapping.Indexed;
import org.springframework.data.solr.core.mapping.SolrDocument;

import com.ascbank.model.base.PKEntity;

@SolrDocument(solrCoreName = "gettingstarted")
public class Article extends PKEntity<Long> {
	/**
	 * 
	 */
	private static final long serialVersionUID = 7336704674702749908L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column article.clicks
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	@Field
	private Short clicks;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column article.context
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	@Field
	@Indexed(type = "txt_hp_cn")
	private String context;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column article.menu_id
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	@Field
	private Long menuId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column article.uploadtime
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	@Field
	private Date uploadtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column article.clicks
	 *
	 * @return the value of article.clicks
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	public Short getClicks() {
		return clicks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column article.clicks
	 *
	 * @param clicks
	 *            the value for article.clicks
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	public void setClicks(Short clicks) {
		this.clicks = clicks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column article.context
	 *
	 * @return the value of article.context
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	public String getContext() {
		return context;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column article.context
	 *
	 * @param context
	 *            the value for article.context
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	public void setContext(String context) {
		this.context = context == null ? null : context.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column article.menu_id
	 *
	 * @return the value of article.menu_id
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	public Long getMenuId() {
		return menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column article.menu_id
	 *
	 * @param menuId
	 *            the value for article.menu_id
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	public void setMenuId(Long menuId) {
		this.menuId = menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column article.uploadtime
	 *
	 * @return the value of article.uploadtime
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	public Date getUploadtime() {
		return uploadtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column article.uploadtime
	 *
	 * @param uploadtime
	 *            the value for article.uploadtime
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	public void setUploadtime(Date uploadtime) {
		this.uploadtime = uploadtime;
	}

	@Override
	public String toString() {
		return "Article [id=" + getId() + ", clicks=" + clicks + ", context=" + context + ", menuId=" + menuId + ", uploadtime=" + uploadtime + "]";
	}

}