package com.ascbank.model;

import com.ascbank.model.base.PKEntity;
import com.fasterxml.jackson.annotation.JsonProperty;

public class Dependencies extends PKEntity<Long> {
	/**
	 *
	 */
	private static final long	serialVersionUID	= -8713972186548326207L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_dependencies.from_id
	 *
	 * @mbggenerated Mon Oct 31 10:47:16 CST 2016
	 */
	// @JsonIgnore
	private Long				fromId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_dependencies.to_id
	 *
	 * @mbggenerated Mon Oct 31 10:47:16 CST 2016
	 */
	@JsonProperty("to")
	private Long				toId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_dependencies.from_id
	 *
	 * @return the value of t_dependencies.from_id
	 *
	 * @mbggenerated Mon Oct 31 10:47:16 CST 2016
	 */
	public Long getFromId() {
		return fromId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_dependencies.to_id
	 *
	 * @return the value of t_dependencies.to_id
	 *
	 * @mbggenerated Mon Oct 31 10:47:16 CST 2016
	 */
	public Long getToId() {
		return toId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_dependencies.from_id
	 *
	 * @param fromId
	 *            the value for t_dependencies.from_id
	 *
	 * @mbggenerated Mon Oct 31 10:47:16 CST 2016
	 */
	public void setFromId(Long fromId) {
		this.fromId = fromId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_dependencies.to_id
	 *
	 * @param toId
	 *            the value for t_dependencies.to_id
	 *
	 * @mbggenerated Mon Oct 31 10:47:16 CST 2016
	 */
	public void setToId(Long toId) {
		this.toId = toId;
	}
}