package com.ascbank.model;

import java.util.Date;

public class Gantt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gantt.id
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gantt.parent_id
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gantt.description
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gantt.duration
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    private Short duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gantt.expanded
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    private Boolean expanded;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gantt.is_live
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    private Boolean isLive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gantt.leaf
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    private Boolean leaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gantt.progress
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    private Double progress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gantt.sort
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    private Short sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gantt.start_date
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gantt.title
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gantt.id
     *
     * @return the value of gantt.id
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gantt.id
     *
     * @param id the value for gantt.id
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gantt.parent_id
     *
     * @return the value of gantt.parent_id
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gantt.parent_id
     *
     * @param parentId the value for gantt.parent_id
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gantt.description
     *
     * @return the value of gantt.description
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gantt.description
     *
     * @param description the value for gantt.description
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gantt.duration
     *
     * @return the value of gantt.duration
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public Short getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gantt.duration
     *
     * @param duration the value for gantt.duration
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public void setDuration(Short duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gantt.expanded
     *
     * @return the value of gantt.expanded
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public Boolean getExpanded() {
        return expanded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gantt.expanded
     *
     * @param expanded the value for gantt.expanded
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public void setExpanded(Boolean expanded) {
        this.expanded = expanded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gantt.is_live
     *
     * @return the value of gantt.is_live
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public Boolean getIsLive() {
        return isLive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gantt.is_live
     *
     * @param isLive the value for gantt.is_live
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public void setIsLive(Boolean isLive) {
        this.isLive = isLive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gantt.leaf
     *
     * @return the value of gantt.leaf
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public Boolean getLeaf() {
        return leaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gantt.leaf
     *
     * @param leaf the value for gantt.leaf
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public void setLeaf(Boolean leaf) {
        this.leaf = leaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gantt.progress
     *
     * @return the value of gantt.progress
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public Double getProgress() {
        return progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gantt.progress
     *
     * @param progress the value for gantt.progress
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public void setProgress(Double progress) {
        this.progress = progress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gantt.sort
     *
     * @return the value of gantt.sort
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public Short getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gantt.sort
     *
     * @param sort the value for gantt.sort
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public void setSort(Short sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gantt.start_date
     *
     * @return the value of gantt.start_date
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gantt.start_date
     *
     * @param startDate the value for gantt.start_date
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gantt.title
     *
     * @return the value of gantt.title
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gantt.title
     *
     * @param title the value for gantt.title
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public void setTitle(String title) {
        this.title = title;
    }
}