package com.ascbank.model;

import java.util.Date;

import com.ascbank.model.base.TreeEntity;

public class Gantt extends TreeEntity<Long, Gantt> {
	/**
	 *
	 */
	private static final long	serialVersionUID	= 1659615191769914526L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_gantt.classes
	 *
	 * @mbggenerated Tue Oct 18 14:02:37 CST 2016
	 */
	private String				classes;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_gantt.color
	 *
	 * @mbggenerated Tue Oct 18 14:02:37 CST 2016
	 */
	private String				color;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_gantt.description
	 *
	 * @mbggenerated Tue Oct 18 14:02:37 CST 2016
	 */
	private String				description;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_gantt.from
	 *
	 * @mbggenerated Tue Oct 18 14:02:37 CST 2016
	 */
	private Date				from;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_gantt.is_live
	 *
	 * @mbggenerated Tue Oct 18 14:02:37 CST 2016
	 */
	private Boolean				isLive;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_gantt.name
	 *
	 * @mbggenerated Tue Oct 18 14:02:37 CST 2016
	 */
	private String				name;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_gantt.progress
	 *
	 * @mbggenerated Tue Oct 18 14:02:37 CST 2016
	 */
	private Integer				progress;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_gantt.sort
	 *
	 * @mbggenerated Tue Oct 18 14:02:37 CST 2016
	 */
	private Short				sort;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_gantt.to
	 *
	 * @mbggenerated Tue Oct 18 14:02:37 CST 2016
	 */
	private Date				to;
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_gantt.classes
	 *
	 * @return the value of t_gantt.classes
	 *
	 * @mbggenerated Tue Oct 18 14:02:37 CST 2016
	 */
	public String getClasses() {
		return classes;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_gantt.color
	 *
	 * @return the value of t_gantt.color
	 *
	 * @mbggenerated Tue Oct 18 14:02:37 CST 2016
	 */
	public String getColor() {
		return color;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_gantt.description
	 *
	 * @return the value of t_gantt.description
	 *
	 * @mbggenerated Tue Oct 18 14:02:37 CST 2016
	 */
	public String getDescription() {
		return description;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_gantt.from
	 *
	 * @return the value of t_gantt.from
	 *
	 * @mbggenerated Tue Oct 18 14:02:37 CST 2016
	 */
	public Date getFrom() {
		return from;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_gantt.is_live
	 *
	 * @return the value of t_gantt.is_live
	 *
	 * @mbggenerated Tue Oct 18 14:02:37 CST 2016
	 */
	public Boolean getIsLive() {
		return isLive;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_gantt.name
	 *
	 * @return the value of t_gantt.name
	 *
	 * @mbggenerated Tue Oct 18 14:02:37 CST 2016
	 */
	public String getName() {
		return name;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_gantt.progress
	 *
	 * @return the value of t_gantt.progress
	 *
	 * @mbggenerated Tue Oct 18 14:02:37 CST 2016
	 */
	public Integer getProgress() {
		return progress;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_gantt.sort
	 *
	 * @return the value of t_gantt.sort
	 *
	 * @mbggenerated Tue Oct 18 14:02:37 CST 2016
	 */
	public Short getSort() {
		return sort;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_gantt.to
	 *
	 * @return the value of t_gantt.to
	 *
	 * @mbggenerated Tue Oct 18 14:02:37 CST 2016
	 */
	public Date getTo() {
		return to;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_gantt.classes
	 *
	 * @param classes
	 *            the value for t_gantt.classes
	 *
	 * @mbggenerated Tue Oct 18 14:02:37 CST 2016
	 */
	public void setClasses(String classes) {
		this.classes = classes == null ? null : classes.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_gantt.color
	 *
	 * @param color
	 *            the value for t_gantt.color
	 *
	 * @mbggenerated Tue Oct 18 14:02:37 CST 2016
	 */
	public void setColor(String color) {
		this.color = color == null ? null : color.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_gantt.description
	 *
	 * @param description
	 *            the value for t_gantt.description
	 *
	 * @mbggenerated Tue Oct 18 14:02:37 CST 2016
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_gantt.from
	 *
	 * @param from
	 *            the value for t_gantt.from
	 *
	 * @mbggenerated Tue Oct 18 14:02:37 CST 2016
	 */
	public void setFrom(Date from) {
		this.from = from;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_gantt.is_live
	 *
	 * @param isLive
	 *            the value for t_gantt.is_live
	 *
	 * @mbggenerated Tue Oct 18 14:02:37 CST 2016
	 */
	public void setIsLive(Boolean isLive) {
		this.isLive = isLive;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_gantt.name
	 *
	 * @param name
	 *            the value for t_gantt.name
	 *
	 * @mbggenerated Tue Oct 18 14:02:37 CST 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_gantt.progress
	 *
	 * @param progress
	 *            the value for t_gantt.progress
	 *
	 * @mbggenerated Tue Oct 18 14:02:37 CST 2016
	 */
	public void setProgress(Integer progress) {
		this.progress = progress;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_gantt.sort
	 *
	 * @param sort
	 *            the value for t_gantt.sort
	 *
	 * @mbggenerated Tue Oct 18 14:02:37 CST 2016
	 */
	public void setSort(Short sort) {
		this.sort = sort;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_gantt.to
	 *
	 * @param to
	 *            the value for t_gantt.to
	 *
	 * @mbggenerated Tue Oct 18 14:02:37 CST 2016
	 */
	public void setTo(Date to) {
		this.to = to;
	}
}