package com.ascbank.model;

import com.ascbank.model.base.PKEntity;

public class Permission extends PKEntity<Long> {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column permission.description
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	private String description;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column permission.entity_ids
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	private String entityIds;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column permission.name
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column permission.permission
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	private String permission;

	

	public Permission(String entityIds, String name, String permission,String description) {
		super();
		this.description = description;
		this.entityIds = entityIds;
		this.name = name;
		this.permission = permission;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column permission.description
	 *
	 * @return the value of permission.description
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column permission.description
	 *
	 * @param description
	 *            the value for permission.description
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column permission.entity_ids
	 *
	 * @return the value of permission.entity_ids
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	public String getEntityIds() {
		return entityIds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column permission.entity_ids
	 *
	 * @param entityIds
	 *            the value for permission.entity_ids
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	public void setEntityIds(String entityIds) {
		this.entityIds = entityIds == null ? null : entityIds.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column permission.name
	 *
	 * @return the value of permission.name
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column permission.name
	 *
	 * @param name
	 *            the value for permission.name
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column permission.permission
	 *
	 * @return the value of permission.permission
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	public String getPermission() {
		return permission;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column permission.permission
	 *
	 * @param permission
	 *            the value for permission.permission
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	public void setPermission(String permission) {
		this.permission = permission == null ? null : permission.trim();
	}

	public String toPermissionString() {
		// TODO Auto-generated method stub
		return null;
	}
}