package com.ascbank.model;

import java.util.List;

import com.ascbank.model.base.TreeEntity;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonInclude(value = Include.NON_NULL)
public class Project extends TreeEntity<Long, Project> {
	/**
	 *
	 */
	private static final long	serialVersionUID	= -6504357048970423030L;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_project.classes
	 *
	 * @mbggenerated Thu Oct 20 10:03:04 CST 2016
	 */
	private String				classes;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_project.color
	 *
	 * @mbggenerated Thu Oct 20 10:03:04 CST 2016
	 */
	private String				color;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_project.content
	 *
	 * @mbggenerated Thu Oct 20 10:03:04 CST 2016
	 */
	private String				content;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_project.height
	 *
	 * @mbggenerated Thu Oct 20 10:03:04 CST 2016
	 */
	private String				height;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_project.name
	 *
	 * @mbggenerated Thu Oct 20 10:03:04 CST 2016
	 */
	private String				name;

	private List<Task>			tasks;
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_project.classes
	 *
	 * @return the value of t_project.classes
	 *
	 * @mbggenerated Thu Oct 20 10:03:04 CST 2016
	 */
	public String getClasses() {
		return classes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_project.color
	 *
	 * @return the value of t_project.color
	 *
	 * @mbggenerated Thu Oct 20 10:03:04 CST 2016
	 */
	public String getColor() {
		return color;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_project.content
	 *
	 * @return the value of t_project.content
	 *
	 * @mbggenerated Thu Oct 20 10:03:04 CST 2016
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_project.height
	 *
	 * @return the value of t_project.height
	 *
	 * @mbggenerated Thu Oct 20 10:03:04 CST 2016
	 */
	public String getHeight() {
		return height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_project.name
	 *
	 * @return the value of t_project.name
	 *
	 * @mbggenerated Thu Oct 20 10:03:04 CST 2016
	 */
	public String getName() {
		return name;
	}

	/*
	 * (non-Javadoc)
	 *
	 * @see com.ascbank.model.base.TreeEntity#getParentId()
	 */

	@Override
	@JsonProperty("parent")
	public Long getParentId() {
		// TODO Auto-generated method stub
		return super.getParentId();
	}

	/**
	 * @return the tasks
	 */
	public List<Task> getTasks() {
		return tasks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_project.classes
	 *
	 * @param classes
	 *            the value for t_project.classes
	 *
	 * @mbggenerated Thu Oct 20 10:03:04 CST 2016
	 */
	public void setClasses(String classes) {
		this.classes = classes == null ? null : classes.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_project.color
	 *
	 * @param color
	 *            the value for t_project.color
	 *
	 * @mbggenerated Thu Oct 20 10:03:04 CST 2016
	 */
	public void setColor(String color) {
		this.color = color == null ? null : color.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_project.content
	 *
	 * @param content
	 *            the value for t_project.content
	 *
	 * @mbggenerated Thu Oct 20 10:03:04 CST 2016
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_project.height
	 *
	 * @param height
	 *            the value for t_project.height
	 *
	 * @mbggenerated Thu Oct 20 10:03:04 CST 2016
	 */
	public void setHeight(String height) {
		this.height = height == null ? null : height.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_project.name
	 *
	 * @param name
	 *            the value for t_project.name
	 *
	 * @mbggenerated Thu Oct 20 10:03:04 CST 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * @param tasks
	 *            the tasks to set
	 */
	public void setTasks(List<Task> tasks) {
		this.tasks = tasks;
	}
	
	/*
	 * (non-Javadoc)
	 *
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Project [classes=" + classes + ", color=" + color + ", content=" + content + ", height=" + height + ", name=" + name + ", getChildren()=" + getChildren() + ", getParentId()=" + getParentId() + ", getStem()=" + getStem() + ", getId()=" + getId() + ", hashCode()=" + hashCode() + ", isNew()=" + isNew() + ", toString()=" + super.toString() + ", getClass()=" + getClass() + "]";
	}
	
}