package com.ascbank.model;

import java.util.List;

import com.ascbank.model.base.PKEntity;

public class Role extends PKEntity<Long> {

	private static final long serialVersionUID = 8278525185005105435L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column role.description
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	private String description;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column role.role_name
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	private String roleName;

	public Role(String username, String description) {
		// TODO Auto-generated constructor stub
		this.roleName = username;
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column role.description
	 *
	 * @return the value of role.description
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column role.description
	 *
	 * @param description
	 *            the value for role.description
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column role.role_name
	 *
	 * @return the value of role.role_name
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column role.role_name
	 *
	 * @param roleName
	 *            the value for role.role_name
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName == null ? null : roleName.trim();
	}

	public List<Permission> getPermissions() {
		// TODO Auto-generated method stub
		return null;
	}
}