package com.ascbank.model;

public class Shortcut {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shortcut.id
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shortcut.app_class
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    private String appClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shortcut.icon_cls
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    private String iconCls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shortcut.module
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    private String module;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shortcut.name
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shortcut.id
     *
     * @return the value of shortcut.id
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shortcut.id
     *
     * @param id the value for shortcut.id
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shortcut.app_class
     *
     * @return the value of shortcut.app_class
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public String getAppClass() {
        return appClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shortcut.app_class
     *
     * @param appClass the value for shortcut.app_class
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public void setAppClass(String appClass) {
        this.appClass = appClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shortcut.icon_cls
     *
     * @return the value of shortcut.icon_cls
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public String getIconCls() {
        return iconCls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shortcut.icon_cls
     *
     * @param iconCls the value for shortcut.icon_cls
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public void setIconCls(String iconCls) {
        this.iconCls = iconCls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shortcut.module
     *
     * @return the value of shortcut.module
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public String getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shortcut.module
     *
     * @param module the value for shortcut.module
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public void setModule(String module) {
        this.module = module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shortcut.name
     *
     * @return the value of shortcut.name
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shortcut.name
     *
     * @param name the value for shortcut.name
     *
     * @mbggenerated Mon Jun 06 16:44:46 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }
}