package com.ascbank.model;

import com.ascbank.model.base.PKEntity;

public class SystemInfo extends PKEntity<Long> {
	/**
	 *
	 */
	private static final long	serialVersionUID	= 8504736711029628468L;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_info.description
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	private String				description;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_info.keyname
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	private String				keyname;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_info.organize
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	private String				organize;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_info.type
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	private String				type;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column system_info.value
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	private String				value;
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_info.description
	 *
	 * @return the value of system_info.description
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	public String getDescription() {
		return description;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_info.keyname
	 *
	 * @return the value of system_info.keyname
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	public String getKeyname() {
		return keyname;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_info.organize
	 *
	 * @return the value of system_info.organize
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	public String getOrganize() {
		return organize;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_info.type
	 *
	 * @return the value of system_info.type
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	public String getType() {
		return type;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column system_info.value
	 *
	 * @return the value of system_info.value
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	public String getValue() {
		return value;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_info.description
	 *
	 * @param description
	 *            the value for system_info.description
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_info.keyname
	 *
	 * @param keyname
	 *            the value for system_info.keyname
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	public void setKeyname(String keyname) {
		this.keyname = keyname == null ? null : keyname.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_info.organize
	 *
	 * @param organize
	 *            the value for system_info.organize
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	public void setOrganize(String organize) {
		this.organize = organize == null ? null : organize.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_info.type
	 *
	 * @param type
	 *            the value for system_info.type
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column system_info.value
	 *
	 * @param value
	 *            the value for system_info.value
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	public void setValue(String value) {
		this.value = value == null ? null : value.trim();
	}
}