package com.ascbank.model;

import java.util.Date;

import com.ascbank.model.base.PKEntity;

public class Task extends PKEntity<Long> {
	/**
	 *
	 */
	private static final long	serialVersionUID	= 862979892688947879L;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_task.classes
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	private String				classes;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_task.color
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	private String				color;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_task.description
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	private String				description;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_task.from
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	private Date				from;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_task.id
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	private Long				id;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_task.is_live
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	private Boolean				isLive;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_task.name
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	private String				name;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_task.parent_id
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	private Long				parentId;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_task.progress
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	private Integer				progress;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_task.sort
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	private Short				sort;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_task.stem
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	private String				stem;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_task.to
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	private Date				to;
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_task.classes
	 *
	 * @return the value of t_task.classes
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	public String getClasses() {
		return classes;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_task.color
	 *
	 * @return the value of t_task.color
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	public String getColor() {
		return color;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_task.description
	 *
	 * @return the value of t_task.description
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	public String getDescription() {
		return description;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_task.from
	 *
	 * @return the value of t_task.from
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	public Date getFrom() {
		return from;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_task.id
	 *
	 * @return the value of t_task.id
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	@Override
	public Long getId() {
		return id;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_task.is_live
	 *
	 * @return the value of t_task.is_live
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	public Boolean getIsLive() {
		return isLive;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_task.name
	 *
	 * @return the value of t_task.name
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	public String getName() {
		return name;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_task.parent_id
	 *
	 * @return the value of t_task.parent_id
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	public Long getParentId() {
		return parentId;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_task.progress
	 *
	 * @return the value of t_task.progress
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	public Integer getProgress() {
		return progress;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_task.sort
	 *
	 * @return the value of t_task.sort
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	public Short getSort() {
		return sort;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_task.stem
	 *
	 * @return the value of t_task.stem
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	public String getStem() {
		return stem;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_task.to
	 *
	 * @return the value of t_task.to
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	public Date getTo() {
		return to;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_task.classes
	 *
	 * @param classes
	 *            the value for t_task.classes
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	public void setClasses(String classes) {
		this.classes = classes == null ? null : classes.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_task.color
	 *
	 * @param color
	 *            the value for t_task.color
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	public void setColor(String color) {
		this.color = color == null ? null : color.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_task.description
	 *
	 * @param description
	 *            the value for t_task.description
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_task.from
	 *
	 * @param from
	 *            the value for t_task.from
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	public void setFrom(Date from) {
		this.from = from;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_task.id
	 *
	 * @param id
	 *            the value for t_task.id
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	@Override
	public void setId(Long id) {
		this.id = id;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_task.is_live
	 *
	 * @param isLive
	 *            the value for t_task.is_live
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	public void setIsLive(Boolean isLive) {
		this.isLive = isLive;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_task.name
	 *
	 * @param name
	 *            the value for t_task.name
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_task.parent_id
	 *
	 * @param parentId
	 *            the value for t_task.parent_id
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_task.progress
	 *
	 * @param progress
	 *            the value for t_task.progress
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	public void setProgress(Integer progress) {
		this.progress = progress;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_task.sort
	 *
	 * @param sort
	 *            the value for t_task.sort
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	public void setSort(Short sort) {
		this.sort = sort;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_task.stem
	 *
	 * @param stem
	 *            the value for t_task.stem
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	public void setStem(String stem) {
		this.stem = stem == null ? null : stem.trim();
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_task.to
	 *
	 * @param to
	 *            the value for t_task.to
	 *
	 * @mbggenerated Wed Oct 19 09:56:36 CST 2016
	 */
	public void setTo(Date to) {
		this.to = to;
	}
}