package com.ascbank.model;

public class TDependencies {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dependencies.from_id
     *
     * @mbggenerated Mon Oct 31 13:13:00 CST 2016
     */
    private Long fromId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dependencies.to_id
     *
     * @mbggenerated Mon Oct 31 13:13:00 CST 2016
     */
    private Long toId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dependencies.id
     *
     * @mbggenerated Mon Oct 31 13:13:00 CST 2016
     */
    private Long id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dependencies.from_id
     *
     * @return the value of t_dependencies.from_id
     *
     * @mbggenerated Mon Oct 31 13:13:00 CST 2016
     */
    public Long getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dependencies.from_id
     *
     * @param fromId the value for t_dependencies.from_id
     *
     * @mbggenerated Mon Oct 31 13:13:00 CST 2016
     */
    public void setFromId(Long fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dependencies.to_id
     *
     * @return the value of t_dependencies.to_id
     *
     * @mbggenerated Mon Oct 31 13:13:00 CST 2016
     */
    public Long getToId() {
        return toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dependencies.to_id
     *
     * @param toId the value for t_dependencies.to_id
     *
     * @mbggenerated Mon Oct 31 13:13:00 CST 2016
     */
    public void setToId(Long toId) {
        this.toId = toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dependencies.id
     *
     * @return the value of t_dependencies.id
     *
     * @mbggenerated Mon Oct 31 13:13:00 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dependencies.id
     *
     * @param id the value for t_dependencies.id
     *
     * @mbggenerated Mon Oct 31 13:13:00 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }
}