package com.ascbank.model;

import com.ascbank.model.base.PKEntity;

public class UserRole extends PKEntity<Long> {
	/**
	 *
	 */
	private static final long	serialVersionUID	= 6624775591785630850L;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_role.role_id
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	private Long				roleId;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_role.user_id
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	private Long				userId;
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_role.role_id
	 *
	 * @return the value of user_role.role_id
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	public Long getRoleId() {
		return roleId;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_role.user_id
	 *
	 * @return the value of user_role.user_id
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	public Long getUserId() {
		return userId;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_role.role_id
	 *
	 * @param roleId
	 *            the value for user_role.role_id
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_role.user_id
	 *
	 * @param userId
	 *            the value for user_role.user_id
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}
}