package com.ascbank.dao;

import java.util.List;

import com.ascbank.dao.base.BaseInterfaceDao;
import com.ascbank.model.Article;
import com.ascbank.repository.mybatis.MyBatisRepository;

@MyBatisRepository
public interface ArticleMapper extends BaseInterfaceDao<Long, Article> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	int deleteByPrimaryKey(Long id);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	int insert(Article record);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	List<Article> selectAll();
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	Article selectByPrimaryKey(Long id);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	int updateByPrimaryKey(Article record);
}