package com.ascbank.dao;

import java.util.List;

import com.ascbank.dao.base.BaseInterfaceDao;
import com.ascbank.model.FileInfo;

public interface FileInfoMapper extends BaseInterfaceDao<Long, FileInfo> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_file
	 *
	 * @mbggenerated Tue Oct 18 14:02:37 CST 2016
	 */
	@Override
	int insert(FileInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_file
	 *
	 * @mbggenerated Tue Oct 18 14:02:37 CST 2016
	 */
	@Override
	List<FileInfo> selectAll();
}