package com.ascbank.dao;

import com.ascbank.model.Gantt;
import com.ascbank.repository.mybatis.MyBatisRepository;

@MyBatisRepository
public interface GanttMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gantt
     *
     * @mbggenerated Tue Jun 07 15:09:14 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gantt
     *
     * @mbggenerated Tue Jun 07 15:09:14 CST 2016
     */
    int insert(Gantt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gantt
     *
     * @mbggenerated Tue Jun 07 15:09:14 CST 2016
     */
    int insertSelective(Gantt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gantt
     *
     * @mbggenerated Tue Jun 07 15:09:14 CST 2016
     */
    Gantt selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gantt
     *
     * @mbggenerated Tue Jun 07 15:09:14 CST 2016
     */
    int updateByPrimaryKeySelective(Gantt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gantt
     *
     * @mbggenerated Tue Jun 07 15:09:14 CST 2016
     */
    int updateByPrimaryKey(Gantt record);
}