package com.ascbank.dao;

import java.util.List;

import com.ascbank.dao.base.BaseInterfaceDao;
import com.ascbank.model.Navigation;
import com.ascbank.repository.mybatis.MyBatisRepository;

@MyBatisRepository
public interface NavigationMapper extends BaseInterfaceDao<Long, Navigation> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table navigation
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	int deleteByPrimaryKey(Long id);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table navigation
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	int insert(Navigation record);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table navigation
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	List<Navigation> selectAll();
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table navigation
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	Navigation selectByPrimaryKey(Long id);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table navigation
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	int updateByPrimaryKey(Navigation record);
}