package com.ascbank.dao;

import java.util.List;

import com.ascbank.dao.base.BaseInterfaceDao;
import com.ascbank.model.Permission;
import com.ascbank.repository.mybatis.MyBatisRepository;

@MyBatisRepository
public interface PermissionMapper extends BaseInterfaceDao<Long, Permission> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	int deleteByPrimaryKey(Long id);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	int insert(Permission record);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	List<Permission> selectAll();
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	Permission selectByPrimaryKey(Long id);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table permission
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	int updateByPrimaryKey(Permission record);
}