package com.ascbank.dao;

import com.ascbank.dao.base.BaseInterfaceDao;
import com.ascbank.model.Project;

public interface ProjectMapper extends BaseInterfaceDao<Long, Project> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_project
	 *
	 * @mbggenerated Wed Oct 19 10:01:03 CST 2016
	 */
	@Override
	int deleteByPrimaryKey(Long id);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_project
	 *
	 * @mbggenerated Wed Oct 19 10:01:03 CST 2016
	 */
	@Override
	int insert(Project record);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_project
	 *
	 * @mbggenerated Wed Oct 19 10:01:03 CST 2016
	 */
	@Override
	int insertSelective(Project record);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_project
	 *
	 * @mbggenerated Wed Oct 19 10:01:03 CST 2016
	 */
	@Override
	Project selectByPrimaryKey(Long id);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_project
	 *
	 * @mbggenerated Wed Oct 19 10:01:03 CST 2016
	 */
	@Override
	int updateByPrimaryKey(Project record);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_project
	 *
	 * @mbggenerated Wed Oct 19 10:01:03 CST 2016
	 */
	@Override
	int updateByPrimaryKeySelective(Project record);
}