package com.ascbank.dao;

import java.util.List;

import com.ascbank.dao.base.BaseInterfaceDao;
import com.ascbank.model.Role;
import com.ascbank.repository.mybatis.MyBatisRepository;

@MyBatisRepository
public interface RoleMapper extends BaseInterfaceDao<Long, Role> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	int deleteByPrimaryKey(Long id);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	int insert(Role record);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	List<Role> selectAll();
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	Role selectByPrimaryKey(Long id);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table role
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	int updateByPrimaryKey(Role record);
}