package com.ascbank.dao;

import com.ascbank.model.Shortcut;
import com.ascbank.repository.mybatis.MyBatisRepository;

@MyBatisRepository
public interface ShortcutMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shortcut
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shortcut
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	int insert(Shortcut record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shortcut
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	int insertSelective(Shortcut record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shortcut
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	Shortcut selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shortcut
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	int updateByPrimaryKeySelective(Shortcut record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table shortcut
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	int updateByPrimaryKey(Shortcut record);
}