package com.ascbank.dao;

import java.util.List;

import com.ascbank.dao.base.BaseInterfaceDao;
import com.ascbank.model.Shortcut;
import com.ascbank.repository.mybatis.MyBatisRepository;

@MyBatisRepository
public interface ShortcutMapper extends BaseInterfaceDao<Long, Shortcut> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shortcut
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	int deleteByPrimaryKey(Long id);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shortcut
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	int insert(Shortcut record);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shortcut
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	List<Shortcut> selectAll();
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shortcut
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	Shortcut selectByPrimaryKey(Long id);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shortcut
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	int updateByPrimaryKey(Shortcut record);
}