package com.ascbank.dao;

import java.util.List;

import com.ascbank.dao.base.BaseInterfaceDao;
import com.ascbank.model.SystemInfo;
import com.ascbank.repository.mybatis.MyBatisRepository;

@MyBatisRepository
public interface SystemInfoMapper extends BaseInterfaceDao<Long, SystemInfo> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table system_info
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	int deleteByPrimaryKey(Long id);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table system_info
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	int insert(SystemInfo record);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table system_info
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	List<SystemInfo> selectAll();
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table system_info
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	SystemInfo selectByPrimaryKey(Long id);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table system_info
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	int updateByPrimaryKey(SystemInfo record);
}