package com.ascbank.dao;

import com.ascbank.dao.base.BaseInterfaceDao;
import com.ascbank.model.Task;

public interface TaskMapper extends BaseInterfaceDao<Long, Task> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_task
	 *
	 * @mbggenerated Wed Oct 19 10:01:03 CST 2016
	 */
	@Override
	int deleteByPrimaryKey(Long id);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_task
	 *
	 * @mbggenerated Wed Oct 19 10:01:03 CST 2016
	 */
	@Override
	int insert(Task record);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_task
	 *
	 * @mbggenerated Wed Oct 19 10:01:03 CST 2016
	 */
	@Override
	int insertSelective(Task record);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_task
	 *
	 * @mbggenerated Wed Oct 19 10:01:03 CST 2016
	 */
	@Override
	Task selectByPrimaryKey(Long id);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_task
	 *
	 * @mbggenerated Wed Oct 19 10:01:03 CST 2016
	 */
	@Override
	int updateByPrimaryKey(Task record);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_task
	 *
	 * @mbggenerated Wed Oct 19 10:01:03 CST 2016
	 */
	@Override
	int updateByPrimaryKeySelective(Task record);
}