package com.ascbank.dao;

import java.util.List;

import com.ascbank.dao.base.BaseInterfaceDao;
import com.ascbank.model.Task;
import com.ascbank.repository.mybatis.MyBatisRepository;

@MyBatisRepository
public interface TaskMapper extends BaseInterfaceDao<Long, Task> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_task
	 *
	 * @mbggenerated Thu Oct 20 10:03:04 CST 2016
	 */
	@Override
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_task
	 *
	 * @mbggenerated Thu Oct 20 10:03:04 CST 2016
	 */
	@Override
	int insert(Task record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_task
	 *
	 * @mbggenerated Thu Oct 20 10:03:04 CST 2016
	 */
	@Override
	int insertSelective(Task record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_task
	 *
	 * @mbggenerated Thu Oct 20 10:03:04 CST 2016
	 */
	@Override
	Task selectByPrimaryKey(Long id);

	List<Task> selelctByParentId(Long parentid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_task
	 *
	 * @mbggenerated Thu Oct 20 10:03:04 CST 2016
	 */
	@Override
	int updateByPrimaryKey(Task record);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_task
	 *
	 * @mbggenerated Thu Oct 20 10:03:04 CST 2016
	 */
	@Override
	int updateByPrimaryKeySelective(Task record);
}