package com.ascbank.dao;

import com.ascbank.model.UrlFilter;
import com.ascbank.repository.mybatis.MyBatisRepository;

@MyBatisRepository
public interface UrlFilterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_filter
     *
     * @mbggenerated Tue Jun 07 15:09:14 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_filter
     *
     * @mbggenerated Tue Jun 07 15:09:14 CST 2016
     */
    int insert(UrlFilter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_filter
     *
     * @mbggenerated Tue Jun 07 15:09:14 CST 2016
     */
    int insertSelective(UrlFilter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_filter
     *
     * @mbggenerated Tue Jun 07 15:09:14 CST 2016
     */
    UrlFilter selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_filter
     *
     * @mbggenerated Tue Jun 07 15:09:14 CST 2016
     */
    int updateByPrimaryKeySelective(UrlFilter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table url_filter
     *
     * @mbggenerated Tue Jun 07 15:09:14 CST 2016
     */
    int updateByPrimaryKey(UrlFilter record);
}