package com.ascbank.dao;

import com.ascbank.model.User;
import com.ascbank.repository.mybatis.MyBatisRepository;

@MyBatisRepository
public interface UserMapper extends BaseInterfaceDao<Long, User> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	User selectByPrimaryKey(Long id);

	User selectByUsername(String username);

	User selectByPhone(Long phone);

	User selectByEmail(String email);

}