package com.ascbank.dao;

import com.ascbank.model.UserRole;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Jun 07 15:09:14 CST 2016
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Jun 07 15:09:14 CST 2016
     */
    int insertSelective(UserRole record);
}