package com.ascbank.dao;

import java.util.List;

import com.ascbank.dao.base.BaseInterfaceDao;
import com.ascbank.model.User;
import com.ascbank.repository.mybatis.MyBatisRepository;

@MyBatisRepository
public interface UserMapper extends BaseInterfaceDao<Long, User> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	int deleteByPrimaryKey(Long id);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	int insert(User record);
	
	@Override
	int insertSelective(User user);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	List<User> selectAll();
	
	User selectByEmail(String email);
	
	User selectByPhone(Long phone);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	User selectByPrimaryKey(Long id);
	
	User selectByUser(User user);
	
	User selectByUsername(String username);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 *
	 * @mbggenerated Wed Jul 13 16:52:44 CST 2016
	 */
	@Override
	int updateByPrimaryKey(User record);
	
	@Override
	int updateByPrimaryKeySelective(User user);
}