package com.ascbank.model;

public class RolePermission {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column role_permission.role_id
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	private Long roleId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column role_permission.permission_id
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	private Long permissionId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column role_permission.role_id
	 *
	 * @return the value of role_permission.role_id
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	public Long getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column role_permission.role_id
	 *
	 * @param roleId
	 *            the value for role_permission.role_id
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column role_permission.permission_id
	 *
	 * @return the value of role_permission.permission_id
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	public Long getPermissionId() {
		return permissionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column role_permission.permission_id
	 *
	 * @param permissionId
	 *            the value for role_permission.permission_id
	 *
	 * @mbggenerated Tue Jun 07 15:09:14 CST 2016
	 */
	public void setPermissionId(Long permissionId) {
		this.permissionId = permissionId;
	}
}